spring.application.name=CityOrbit
server.port=8080

spring.datasource.url=jdbc:h2:mem:cityorbitdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

spring.datasource.password=${CITYORBIT_DB_PASS:cityorbit_h2_dev_2026}

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.webservices.path=/ws

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.level.br.com.fiap.cityorbit=INFO
logging.level.org.springframework.ws=WARN
logging.level.org.springframework.security=WARN

cityorbit.security.jwt.secret=${CITYORBIT_JWT_SECRET:CityOrbit2026FiapGlobalSolutionSecretKeyForJwtSigningHS256MinLen32}

cityorbit.security.jwt.expiration=${CITYORBIT_JWT_EXPIRATION:28800000}

cityorbit.security.users.admin.username=${CITYORBIT_ADMIN_USER:admin}
cityorbit.security.users.admin.password=${CITYORBIT_ADMIN_PASS:cityorbit2026}
cityorbit.security.users.admin.role=ADMIN

cityorbit.security.users.viewer.username=${CITYORBIT_VIEWER_USER:viewer}
cityorbit.security.users.viewer.password=${CITYORBIT_VIEWER_PASS:view2026}
cityorbit.security.users.viewer.role=VIEWER

cityorbit.security.rate-limit.read-rpm=${RATE_LIMIT_READ:120}
cityorbit.security.rate-limit.write-rpm=${RATE_LIMIT_WRITE:30}

cityorbit.security.incident.notification.recipients=${INCIDENT_NOTIFY_RECIPIENTS:admin@cityorbit.fiap.br,security@cityorbit.fiap.br}
cityorbit.security.incident.notification.anpd-email=${ANPD_EMAIL:incidentes@anpd.gov.br}

cityorbit.security.mfa.required-for-admins=${MFA_REQUIRED_FOR_ADMINS:true}

cityorbit.security.cors.allowed-origins=${CITYORBIT_CORS_ORIGINS:http://localhost:8080,http://localhost:3000}
